### ISSUE TITLE
Config.json

### ISSUE THREAD

**Issue by Kopbabakop** [zeeblo/Noriko-bot#5]
Can you explain the config.json please?

**Comment by zeeblo** [comment]
You need to create a `config.json` file in the main folder and paste in your tokens. So for example
Your "Main folder" would be where `main.py` is. Edit the config file and paste in

```js
{
"BOT_TOKEN": "your token",
"GPT_TOKEN": "your token",
"PALM_TOKEN": "your token",
"Key": "Your key"
}
```
Then as you know, replace "your token" with your actual generated token. 

I'm going to be updating this to replace "PALM" once I have time since it is outdated and no longer works
